// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SistemaVendas_MVC;

namespace SistemaVendas_MVC.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("SistemaVendas_MVC.Models.ClienteModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Cpf_Cnpj")
                        .IsRequired();

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("SistemaVendas_MVC.Models.ItemVendaModel", b =>
                {
                    b.Property<int>("Venda_Id");

                    b.Property<int>("Produto_Id");

                    b.Property<string>("DescricaoProduto");

                    b.Property<decimal>("PrecoProduto");

                    b.Property<decimal>("QtdeProduto");

                    b.Property<double>("QtdeVendido");

                    b.Property<decimal>("TotalVenda");

                    b.HasKey("Venda_Id", "Produto_Id");

                    b.HasIndex("Produto_Id");

                    b.ToTable("ItemVendas");
                });

            modelBuilder.Entity("SistemaVendas_MVC.Models.ProdutoModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Descricao")
                        .IsRequired();

                    b.Property<string>("Link_Foto")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<decimal?>("Preco_Unitario")
                        .IsRequired();

                    b.Property<float?>("Quantidade_Estoque")
                        .IsRequired();

                    b.Property<string>("Unidade_Medida")
                        .IsRequired();

                    b.Property<int?>("VendaModelId");

                    b.HasKey("Id");

                    b.HasIndex("VendaModelId");

                    b.ToTable("Produtos");
                });

            modelBuilder.Entity("SistemaVendas_MVC.Models.VendaModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int?>("Cliente_Id");

                    b.Property<DateTime>("Data");

                    b.Property<decimal>("TotalVenda");

                    b.Property<int?>("Vendedor_Id");

                    b.HasKey("Id");

                    b.ToTable("Vendas");
                });

            modelBuilder.Entity("SistemaVendas_MVC.Models.VendedorModel", b =>
                {
                    b.Property<int?>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Nome")
                        .IsRequired();

                    b.Property<string>("Senha");

                    b.HasKey("Id");

                    b.ToTable("Vendedores");
                });

            modelBuilder.Entity("SistemaVendas_MVC.Models.ItemVendaModel", b =>
                {
                    b.HasOne("SistemaVendas_MVC.Models.ProdutoModel", "Produto")
                        .WithMany("Vendas")
                        .HasForeignKey("Produto_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("SistemaVendas_MVC.Models.VendaModel", "Venda")
                        .WithMany("Produtos")
                        .HasForeignKey("Venda_Id")
                        .OnDelete(DeleteBehavior.Cascade);
                });

            modelBuilder.Entity("SistemaVendas_MVC.Models.ProdutoModel", b =>
                {
                    b.HasOne("SistemaVendas_MVC.Models.VendaModel")
                        .WithMany("ListaProdutos")
                        .HasForeignKey("VendaModelId");
                });
#pragma warning restore 612, 618
        }
    }
}
